title: A Blog
description: digital musings.
author: chris

plugins:
  - jekyll-remote-theme

# Theme Settings
remote_theme: pages-themes/minimal@v0.2.0
is_project_page: false
show_downloads: false

# Custom Settings
summarize: true
## Sidebar Settings
github_username: christopherwoodall
linkedin_username: 
twitter_username: telepathicpug
bluesky_username: telepathicpug.com

# Collection Settings
collections:
  notes:
    output: true
    permalink: /notes/:path/
  about:
    output: true
    permalink: /about/:path/
